### ISSUE TITLE
Add `xc7z020clg400-1` part to artifacts

### ISSUE THREAD

**Issue by Asoftyn** [f4pga/f4pga-arch-defs#3058]
It looks like there should be support for this part but there are no artifacts for the part.  https://github.com/f4pga/f4pga-arch-defs/pull/1260 included suport but it was closed not merged. 

Could it be possible to add `xc7z020clg400-1` to the artifacts/assets?

**Comment by tmichalak** [comment]
It has been merged in [f4pga/f4pga-arch-defs#1506](https://github.com/f4pga/f4pga-arch-defs/pull/1506).
The artifacts for can be found in the [releases](https://github.com/f4pga/f4pga-arch-defs/releases/tag/latest).
They seem to work as described in the [thread](https://github.com/chipsalliance/f4pga-examples/issues/26#issuecomment-1352435067). Closing.
